FROM golang:1.20
 
WORKDIR /app
 
COPY backend/go.mod .
COPY backend/go.sum .
 
# airの設定ファイルをコピー
COPY backend/*air.toml .
 
RUN go mod download
 
COPY ./backend .
 
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
 
CMD ["air"]