import "./globals.css";
import SideBar from "../components/SideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-screen">
          {/* Header */}
          <div className="text-center text-xl font-bold border-b">
            <p>Go Watch a Movie!</p>
          </div>

          {/* Main */}
          <div className="flex w-2/1 p-5">
            {/* sideBar */}
            <div className="w-1/5">
              <SideBar />
            </div>

            {/* mainContents */}
            <div className="w-4/5 pl-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
